blank_issues_enabled: false
contact_links:
  - name: Porfirio
    url: https://github.com/PorfirioTramontana
    about: Please open a feature request in the appropriated repository as defined in the CONTRIBUTING file
