name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TOOLS_VERSION: 29.0.3
  apiLevel: 29
  target: default
  arch: x86
  CMDLINE_TOOLS_URL: https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
  nomeemulatore: test


jobs:
  LintTest:
    runs-on: macos
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Autorizzo Gradle
      run: chmod u+x ./gradlew

    - name: Eseguo Lint Test
      run: |
        ./gradlew lint
    - name: Creo cartella per risultati Lint Test
      run: |
        mkdir -p risultatiLintTest
        cp -R app/build/reports/lint-results.html risultatiLintTest
        cp -R app/build/reports/lint-results.xml risultatiLintTest
    - name: Risultati Lint Test
      uses: actions/upload-artifact@v1
      with:
        name: Risultati Lint Test
        path: risultatiLintTest
  
